// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coupon.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	coupon.proto
	coupon_common.proto
	userCoupon.proto

It has these top-level messages:
	CouponInfo
	GetCouponInfoRequest
	GetCouponInfoReply
	GetCouponListReply
	CreateCouponRequest
	CouponInfoReply
	GetCouponListRequest
	Error
	UserCouponInfo
	GetUserCouponListReply
	GetUserCouponListRequest
	GetUserCouponInfoRequest
	GetUserCouponInfoReply
	StuffCouponStuck
	StuffUserCouponRequest
	StuffUserCouponReply
	VerifyCouponRequest
	VerifyCouponReply
	CouponInfoByCodeRequest
	GetVerificationCouponListRequest
	VerificationCouponInfo
	GetVerificationCouponListReply
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CouponInfo struct {
	ShopId       uint64 `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
	Type         uint64 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ValidityType uint64 `protobuf:"varint,4,opt,name=validityType" json:"validityType,omitempty"`
	RelativeTime uint64 `protobuf:"varint,5,opt,name=relativeTime" json:"relativeTime,omitempty"`
	StartTime    string `protobuf:"bytes,6,opt,name=startTime" json:"startTime,omitempty"`
	EndTime      string `protobuf:"bytes,7,opt,name=endTime" json:"endTime,omitempty"`
	Instructions string `protobuf:"bytes,8,opt,name=instructions" json:"instructions,omitempty"`
	CouponId     uint64 `protobuf:"varint,9,opt,name=couponId" json:"couponId,omitempty"`
	CreatedAt    string `protobuf:"bytes,10,opt,name=createdAt" json:"createdAt,omitempty"`
}

func (m *CouponInfo) Reset()                    { *m = CouponInfo{} }
func (m *CouponInfo) String() string            { return proto.CompactTextString(m) }
func (*CouponInfo) ProtoMessage()               {}
func (*CouponInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CouponInfo) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *CouponInfo) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CouponInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CouponInfo) GetValidityType() uint64 {
	if m != nil {
		return m.ValidityType
	}
	return 0
}

func (m *CouponInfo) GetRelativeTime() uint64 {
	if m != nil {
		return m.RelativeTime
	}
	return 0
}

func (m *CouponInfo) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *CouponInfo) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *CouponInfo) GetInstructions() string {
	if m != nil {
		return m.Instructions
	}
	return ""
}

func (m *CouponInfo) GetCouponId() uint64 {
	if m != nil {
		return m.CouponId
	}
	return 0
}

func (m *CouponInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type GetCouponInfoRequest struct {
	CouponId uint64 `protobuf:"varint,1,opt,name=couponId" json:"couponId,omitempty"`
	ShopId   uint64 `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
}

func (m *GetCouponInfoRequest) Reset()                    { *m = GetCouponInfoRequest{} }
func (m *GetCouponInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCouponInfoRequest) ProtoMessage()               {}
func (*GetCouponInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetCouponInfoRequest) GetCouponId() uint64 {
	if m != nil {
		return m.CouponId
	}
	return 0
}

func (m *GetCouponInfoRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetCouponInfoReply struct {
	CouponInfo *CouponInfo `protobuf:"bytes,1,opt,name=couponInfo" json:"couponInfo,omitempty"`
	Err        *Error      `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *GetCouponInfoReply) Reset()                    { *m = GetCouponInfoReply{} }
func (m *GetCouponInfoReply) String() string            { return proto.CompactTextString(m) }
func (*GetCouponInfoReply) ProtoMessage()               {}
func (*GetCouponInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetCouponInfoReply) GetCouponInfo() *CouponInfo {
	if m != nil {
		return m.CouponInfo
	}
	return nil
}

func (m *GetCouponInfoReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetCouponListReply struct {
	CouponList []*CouponInfo `protobuf:"bytes,1,rep,name=couponList" json:"couponList,omitempty"`
	Err        *Error        `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Count      uint64        `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *GetCouponListReply) Reset()                    { *m = GetCouponListReply{} }
func (m *GetCouponListReply) String() string            { return proto.CompactTextString(m) }
func (*GetCouponListReply) ProtoMessage()               {}
func (*GetCouponListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetCouponListReply) GetCouponList() []*CouponInfo {
	if m != nil {
		return m.CouponList
	}
	return nil
}

func (m *GetCouponListReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetCouponListReply) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CreateCouponRequest struct {
	ShopId       uint64 `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
	Type         uint64 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ValidityType uint64 `protobuf:"varint,4,opt,name=validityType" json:"validityType,omitempty"`
	RelativeTime uint64 `protobuf:"varint,5,opt,name=relativeTime" json:"relativeTime,omitempty"`
	StartTime    string `protobuf:"bytes,6,opt,name=startTime" json:"startTime,omitempty"`
	EndTime      string `protobuf:"bytes,7,opt,name=endTime" json:"endTime,omitempty"`
	Instructions string `protobuf:"bytes,8,opt,name=instructions" json:"instructions,omitempty"`
	CouponId     uint64 `protobuf:"varint,9,opt,name=couponId" json:"couponId,omitempty"`
}

func (m *CreateCouponRequest) Reset()                    { *m = CreateCouponRequest{} }
func (m *CreateCouponRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCouponRequest) ProtoMessage()               {}
func (*CreateCouponRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateCouponRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *CreateCouponRequest) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CreateCouponRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCouponRequest) GetValidityType() uint64 {
	if m != nil {
		return m.ValidityType
	}
	return 0
}

func (m *CreateCouponRequest) GetRelativeTime() uint64 {
	if m != nil {
		return m.RelativeTime
	}
	return 0
}

func (m *CreateCouponRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *CreateCouponRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *CreateCouponRequest) GetInstructions() string {
	if m != nil {
		return m.Instructions
	}
	return ""
}

func (m *CreateCouponRequest) GetCouponId() uint64 {
	if m != nil {
		return m.CouponId
	}
	return 0
}

type CouponInfoReply struct {
	Err      *Error `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	CouponId uint64 `protobuf:"varint,2,opt,name=couponId" json:"couponId,omitempty"`
}

func (m *CouponInfoReply) Reset()                    { *m = CouponInfoReply{} }
func (m *CouponInfoReply) String() string            { return proto.CompactTextString(m) }
func (*CouponInfoReply) ProtoMessage()               {}
func (*CouponInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CouponInfoReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *CouponInfoReply) GetCouponId() uint64 {
	if m != nil {
		return m.CouponId
	}
	return 0
}

type GetCouponListRequest struct {
	ShopId       uint64 `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
	Type         uint64 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ValidityType uint64 `protobuf:"varint,4,opt,name=validityType" json:"validityType,omitempty"`
	RelativeTime uint64 `protobuf:"varint,5,opt,name=relativeTime" json:"relativeTime,omitempty"`
	StartTime    string `protobuf:"bytes,6,opt,name=startTime" json:"startTime,omitempty"`
	EndTime      string `protobuf:"bytes,7,opt,name=endTime" json:"endTime,omitempty"`
	Page         uint64 `protobuf:"varint,8,opt,name=page" json:"page,omitempty"`
	PageSize     uint64 `protobuf:"varint,9,opt,name=PageSize" json:"PageSize,omitempty"`
	IsAll        uint32 `protobuf:"varint,10,opt,name=isAll" json:"isAll,omitempty"`
}

func (m *GetCouponListRequest) Reset()                    { *m = GetCouponListRequest{} }
func (m *GetCouponListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCouponListRequest) ProtoMessage()               {}
func (*GetCouponListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetCouponListRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *GetCouponListRequest) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GetCouponListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetCouponListRequest) GetValidityType() uint64 {
	if m != nil {
		return m.ValidityType
	}
	return 0
}

func (m *GetCouponListRequest) GetRelativeTime() uint64 {
	if m != nil {
		return m.RelativeTime
	}
	return 0
}

func (m *GetCouponListRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetCouponListRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *GetCouponListRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCouponListRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetCouponListRequest) GetIsAll() uint32 {
	if m != nil {
		return m.IsAll
	}
	return 0
}

func init() {
	proto.RegisterType((*CouponInfo)(nil), "coupon.pkg.rpc.protos.CouponInfo")
	proto.RegisterType((*GetCouponInfoRequest)(nil), "coupon.pkg.rpc.protos.GetCouponInfoRequest")
	proto.RegisterType((*GetCouponInfoReply)(nil), "coupon.pkg.rpc.protos.GetCouponInfoReply")
	proto.RegisterType((*GetCouponListReply)(nil), "coupon.pkg.rpc.protos.GetCouponListReply")
	proto.RegisterType((*CreateCouponRequest)(nil), "coupon.pkg.rpc.protos.CreateCouponRequest")
	proto.RegisterType((*CouponInfoReply)(nil), "coupon.pkg.rpc.protos.CouponInfoReply")
	proto.RegisterType((*GetCouponListRequest)(nil), "coupon.pkg.rpc.protos.GetCouponListRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ShopCouponController service

type ShopCouponControllerClient interface {
	// 创建优惠券
	CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*CouponInfoReply, error)
	// 优惠券列表
	GetCouponList(ctx context.Context, in *GetCouponListRequest, opts ...grpc.CallOption) (*GetCouponListReply, error)
	// 获取优惠券详情
	GetCouponInfo(ctx context.Context, in *GetCouponInfoRequest, opts ...grpc.CallOption) (*GetCouponInfoReply, error)
	// 编辑优惠券
	ModifyCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*CouponInfoReply, error)
}

type shopCouponControllerClient struct {
	cc *grpc.ClientConn
}

func NewShopCouponControllerClient(cc *grpc.ClientConn) ShopCouponControllerClient {
	return &shopCouponControllerClient{cc}
}

func (c *shopCouponControllerClient) CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*CouponInfoReply, error) {
	out := new(CouponInfoReply)
	err := grpc.Invoke(ctx, "/coupon.pkg.rpc.protos.ShopCouponController/CreateCoupon", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCouponControllerClient) GetCouponList(ctx context.Context, in *GetCouponListRequest, opts ...grpc.CallOption) (*GetCouponListReply, error) {
	out := new(GetCouponListReply)
	err := grpc.Invoke(ctx, "/coupon.pkg.rpc.protos.ShopCouponController/GetCouponList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCouponControllerClient) GetCouponInfo(ctx context.Context, in *GetCouponInfoRequest, opts ...grpc.CallOption) (*GetCouponInfoReply, error) {
	out := new(GetCouponInfoReply)
	err := grpc.Invoke(ctx, "/coupon.pkg.rpc.protos.ShopCouponController/GetCouponInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCouponControllerClient) ModifyCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*CouponInfoReply, error) {
	out := new(CouponInfoReply)
	err := grpc.Invoke(ctx, "/coupon.pkg.rpc.protos.ShopCouponController/ModifyCoupon", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShopCouponController service

type ShopCouponControllerServer interface {
	// 创建优惠券
	CreateCoupon(context.Context, *CreateCouponRequest) (*CouponInfoReply, error)
	// 优惠券列表
	GetCouponList(context.Context, *GetCouponListRequest) (*GetCouponListReply, error)
	// 获取优惠券详情
	GetCouponInfo(context.Context, *GetCouponInfoRequest) (*GetCouponInfoReply, error)
	// 编辑优惠券
	ModifyCoupon(context.Context, *CreateCouponRequest) (*CouponInfoReply, error)
}

func RegisterShopCouponControllerServer(s *grpc.Server, srv ShopCouponControllerServer) {
	s.RegisterService(&_ShopCouponController_serviceDesc, srv)
}

func _ShopCouponController_CreateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopCouponControllerServer).CreateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.pkg.rpc.protos.ShopCouponController/CreateCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopCouponControllerServer).CreateCoupon(ctx, req.(*CreateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopCouponController_GetCouponList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCouponListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopCouponControllerServer).GetCouponList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.pkg.rpc.protos.ShopCouponController/GetCouponList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopCouponControllerServer).GetCouponList(ctx, req.(*GetCouponListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopCouponController_GetCouponInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCouponInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopCouponControllerServer).GetCouponInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.pkg.rpc.protos.ShopCouponController/GetCouponInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopCouponControllerServer).GetCouponInfo(ctx, req.(*GetCouponInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopCouponController_ModifyCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopCouponControllerServer).ModifyCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.pkg.rpc.protos.ShopCouponController/ModifyCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopCouponControllerServer).ModifyCoupon(ctx, req.(*CreateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShopCouponController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coupon.pkg.rpc.protos.ShopCouponController",
	HandlerType: (*ShopCouponControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCoupon",
			Handler:    _ShopCouponController_CreateCoupon_Handler,
		},
		{
			MethodName: "GetCouponList",
			Handler:    _ShopCouponController_GetCouponList_Handler,
		},
		{
			MethodName: "GetCouponInfo",
			Handler:    _ShopCouponController_GetCouponInfo_Handler,
		},
		{
			MethodName: "ModifyCoupon",
			Handler:    _ShopCouponController_ModifyCoupon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coupon.proto",
}

func init() { proto.RegisterFile("coupon.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x8e, 0x9b, 0x26, 0xd3, 0x54, 0x48, 0xd3, 0x80, 0x56, 0x51, 0x0f, 0xc1, 0x07, 0x54,
	0x40, 0xf2, 0x21, 0x7c, 0x41, 0x88, 0x10, 0x0a, 0x02, 0x09, 0xb9, 0x3d, 0x21, 0x21, 0x64, 0xec,
	0x6d, 0xba, 0xc2, 0xf1, 0x9a, 0xf5, 0xa6, 0x52, 0xf8, 0x01, 0xbe, 0x80, 0x1b, 0xfc, 0x00, 0x5f,
	0xc0, 0xe7, 0xa1, 0x9d, 0xad, 0x93, 0x8d, 0xdb, 0x28, 0xed, 0x81, 0x0b, 0x9c, 0xb2, 0xf3, 0x76,
	0x66, 0xde, 0xe4, 0xcd, 0xf3, 0x42, 0x2f, 0x95, 0x8b, 0x52, 0x16, 0x51, 0xa9, 0xa4, 0x96, 0xf8,
	0xa0, 0x8e, 0x3e, 0xcf, 0x22, 0x55, 0xa6, 0x16, 0xad, 0x06, 0x47, 0x16, 0xfe, 0x98, 0xca, 0xf9,
	0xbc, 0xce, 0x0d, 0x7f, 0xf9, 0x00, 0x13, 0xc2, 0xa7, 0xc5, 0xb9, 0xc4, 0x87, 0xd0, 0xae, 0x2e,
	0x64, 0x39, 0xcd, 0x98, 0x37, 0xf4, 0x4e, 0x82, 0xf8, 0x2a, 0x42, 0x84, 0x40, 0x2f, 0x4b, 0xce,
	0x7c, 0x42, 0xe9, 0x6c, 0xb0, 0x22, 0x99, 0x73, 0xd6, 0x1a, 0x7a, 0x27, 0xdd, 0x98, 0xce, 0x18,
	0x42, 0xef, 0x32, 0xc9, 0x45, 0x26, 0xf4, 0xf2, 0xcc, 0xe4, 0x07, 0x94, 0xbf, 0x81, 0x99, 0x1c,
	0xc5, 0xf3, 0x44, 0x8b, 0x4b, 0x7e, 0x26, 0xe6, 0x9c, 0xed, 0xd9, 0x1c, 0x17, 0xc3, 0x63, 0xe8,
	0x56, 0x3a, 0x51, 0x9a, 0x12, 0xda, 0x44, 0xb0, 0x06, 0x90, 0xc1, 0x3e, 0x2f, 0x32, 0xba, 0xdb,
	0xa7, 0xbb, 0x3a, 0x34, 0xbd, 0x45, 0x51, 0x69, 0xb5, 0x48, 0xb5, 0x90, 0x45, 0xc5, 0x3a, 0x74,
	0xbd, 0x81, 0xe1, 0x00, 0x3a, 0x56, 0x89, 0x69, 0xc6, 0xba, 0xc4, 0xbd, 0x8a, 0x0d, 0x6f, 0xaa,
	0x78, 0xa2, 0x79, 0x36, 0xd6, 0x0c, 0x2c, 0xef, 0x0a, 0x08, 0x5f, 0x43, 0xff, 0x15, 0xd7, 0x6b,
	0xb9, 0x62, 0xfe, 0x65, 0xc1, 0x2b, 0xbd, 0xd1, 0xd1, 0x6b, 0x74, 0x5c, 0x2b, 0xea, 0xbb, 0x8a,
	0x86, 0xdf, 0x3c, 0xc0, 0x46, 0xb3, 0x32, 0x5f, 0xe2, 0x18, 0x20, 0x5d, 0x41, 0xd4, 0xec, 0x60,
	0xf4, 0x28, 0xba, 0x71, 0xa1, 0x91, 0x53, 0xeb, 0x14, 0x61, 0x04, 0x2d, 0xae, 0x14, 0xd1, 0x1d,
	0x8c, 0x8e, 0xb7, 0xd4, 0xbe, 0x54, 0x4a, 0xaa, 0xd8, 0x24, 0x86, 0x3f, 0xdd, 0x49, 0xde, 0x88,
	0x4a, 0x37, 0x26, 0x31, 0x10, 0xf3, 0x86, 0xad, 0x3b, 0x4d, 0x62, 0x8a, 0xee, 0x3a, 0x09, 0xf6,
	0x61, 0x2f, 0x95, 0x8b, 0x42, 0x93, 0xa5, 0x82, 0xd8, 0x06, 0xe1, 0x77, 0x1f, 0x8e, 0x26, 0xb4,
	0x03, 0x4b, 0x53, 0xab, 0xfe, 0x9f, 0x7b, 0x35, 0xfc, 0x00, 0xf7, 0x9b, 0xee, 0xb9, 0x12, 0xdc,
	0xbb, 0xad, 0xe0, 0x6e, 0x7b, 0xbf, 0xd1, 0xfe, 0x87, 0xef, 0xb8, 0xdd, 0xda, 0xe2, 0xdf, 0xd0,
	0x1d, 0x21, 0x28, 0x93, 0x19, 0x27, 0xbd, 0x83, 0x98, 0xce, 0x46, 0x88, 0x77, 0xc9, 0x8c, 0x9f,
	0x8a, 0xaf, 0xbc, 0xd6, 0xb9, 0x8e, 0x8d, 0x2b, 0x45, 0x35, 0xce, 0x73, 0x7a, 0x0f, 0x0e, 0x63,
	0x1b, 0x8c, 0x7e, 0xb7, 0xa0, 0x7f, 0x7a, 0x21, 0x4b, 0xab, 0xcf, 0x44, 0x16, 0x5a, 0xc9, 0x3c,
	0xe7, 0x0a, 0x33, 0xe8, 0xb9, 0x6e, 0xc5, 0xa7, 0xdb, 0xbe, 0x99, 0xeb, 0x96, 0x1e, 0x3c, 0xde,
	0xfd, 0x7d, 0x99, 0x3d, 0x87, 0xf7, 0x50, 0xc0, 0xe1, 0xc6, 0x72, 0xf0, 0xd9, 0x96, 0xd2, 0x9b,
	0x56, 0x38, 0x78, 0x72, 0xbb, 0xe4, 0xeb, 0x54, 0xf4, 0xc0, 0xec, 0xa4, 0x72, 0xde, 0xc6, 0xdd,
	0x54, 0xee, 0xbf, 0xca, 0xa0, 0xf7, 0x56, 0x66, 0xe2, 0x7c, 0xf9, 0x37, 0xb5, 0x7b, 0xd1, 0x79,
	0xdf, 0xb6, 0x77, 0x9f, 0xec, 0xef, 0xf3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xf5, 0x25,
	0x59, 0x40, 0x07, 0x00, 0x00,
}
