// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userCoupon.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserCouponStatus int32

const (
	UserCouponStatus_UnUse   UserCouponStatus = 0
	UserCouponStatus_Used    UserCouponStatus = 1
	UserCouponStatus_Expired UserCouponStatus = 2
)

var UserCouponStatus_name = map[int32]string{
	0: "UnUse",
	1: "Used",
	2: "Expired",
}
var UserCouponStatus_value = map[string]int32{
	"UnUse":   0,
	"Used":    1,
	"Expired": 2,
}

func (x UserCouponStatus) String() string {
	return proto.EnumName(UserCouponStatus_name, int32(x))
}
func (UserCouponStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type UserCouponInfo struct {
	CouponInfo       *CouponInfo `protobuf:"bytes,1,opt,name=couponInfo" json:"couponInfo,omitempty"`
	ExpireTime       string      `protobuf:"bytes,2,opt,name=expireTime" json:"expireTime,omitempty"`
	Status           uint32      `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	VerificationTime string      `protobuf:"bytes,4,opt,name=verificationTime" json:"verificationTime,omitempty"`
	CreatedAt        string      `protobuf:"bytes,5,opt,name=createdAt" json:"createdAt,omitempty"`
	Code             uint64      `protobuf:"varint,6,opt,name=code" json:"code,omitempty"`
	Salt             string      `protobuf:"bytes,7,opt,name=salt" json:"salt,omitempty"`
	UserId           uint64      `protobuf:"varint,8,opt,name=userId" json:"userId,omitempty"`
}

func (m *UserCouponInfo) Reset()                    { *m = UserCouponInfo{} }
func (m *UserCouponInfo) String() string            { return proto.CompactTextString(m) }
func (*UserCouponInfo) ProtoMessage()               {}
func (*UserCouponInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *UserCouponInfo) GetCouponInfo() *CouponInfo {
	if m != nil {
		return m.CouponInfo
	}
	return nil
}

func (m *UserCouponInfo) GetExpireTime() string {
	if m != nil {
		return m.ExpireTime
	}
	return ""
}

func (m *UserCouponInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserCouponInfo) GetVerificationTime() string {
	if m != nil {
		return m.VerificationTime
	}
	return ""
}

func (m *UserCouponInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *UserCouponInfo) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserCouponInfo) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *UserCouponInfo) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserCouponListReply struct {
	UserCouponInfo []*UserCouponInfo `protobuf:"bytes,1,rep,name=userCouponInfo" json:"userCouponInfo,omitempty"`
	Err            *Error            `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	Count          uint32            `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *GetUserCouponListReply) Reset()                    { *m = GetUserCouponListReply{} }
func (m *GetUserCouponListReply) String() string            { return proto.CompactTextString(m) }
func (*GetUserCouponListReply) ProtoMessage()               {}
func (*GetUserCouponListReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *GetUserCouponListReply) GetUserCouponInfo() []*UserCouponInfo {
	if m != nil {
		return m.UserCouponInfo
	}
	return nil
}

func (m *GetUserCouponListReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetUserCouponListReply) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetUserCouponListRequest struct {
	ShopId   uint64 `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
	UserId   uint64 `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	Status   uint32 `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	LastCode string `protobuf:"bytes,4,opt,name=lastCode" json:"lastCode,omitempty"`
	PageSize uint32 `protobuf:"varint,5,opt,name=pageSize" json:"pageSize,omitempty"`
}

func (m *GetUserCouponListRequest) Reset()                    { *m = GetUserCouponListRequest{} }
func (m *GetUserCouponListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserCouponListRequest) ProtoMessage()               {}
func (*GetUserCouponListRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *GetUserCouponListRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *GetUserCouponListRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserCouponListRequest) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetUserCouponListRequest) GetLastCode() string {
	if m != nil {
		return m.LastCode
	}
	return ""
}

func (m *GetUserCouponListRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type GetUserCouponInfoRequest struct {
	Code   uint64 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	ShopId uint64 `protobuf:"varint,3,opt,name=shopId" json:"shopId,omitempty"`
}

func (m *GetUserCouponInfoRequest) Reset()                    { *m = GetUserCouponInfoRequest{} }
func (m *GetUserCouponInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserCouponInfoRequest) ProtoMessage()               {}
func (*GetUserCouponInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GetUserCouponInfoRequest) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetUserCouponInfoRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserCouponInfoRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetUserCouponInfoReply struct {
	UserCouponInfo *UserCouponInfo `protobuf:"bytes,1,opt,name=userCouponInfo" json:"userCouponInfo,omitempty"`
	Err            *Error          `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *GetUserCouponInfoReply) Reset()                    { *m = GetUserCouponInfoReply{} }
func (m *GetUserCouponInfoReply) String() string            { return proto.CompactTextString(m) }
func (*GetUserCouponInfoReply) ProtoMessage()               {}
func (*GetUserCouponInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *GetUserCouponInfoReply) GetUserCouponInfo() *UserCouponInfo {
	if m != nil {
		return m.UserCouponInfo
	}
	return nil
}

func (m *GetUserCouponInfoReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type StuffCouponStuck struct {
	CouponId uint64 `protobuf:"varint,1,opt,name=couponId" json:"couponId,omitempty"`
	Nums     uint32 `protobuf:"varint,2,opt,name=nums" json:"nums,omitempty"`
}

func (m *StuffCouponStuck) Reset()                    { *m = StuffCouponStuck{} }
func (m *StuffCouponStuck) String() string            { return proto.CompactTextString(m) }
func (*StuffCouponStuck) ProtoMessage()               {}
func (*StuffCouponStuck) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *StuffCouponStuck) GetCouponId() uint64 {
	if m != nil {
		return m.CouponId
	}
	return 0
}

func (m *StuffCouponStuck) GetNums() uint32 {
	if m != nil {
		return m.Nums
	}
	return 0
}

type StuffUserCouponRequest struct {
	StuffCouponStuck []*StuffCouponStuck `protobuf:"bytes,1,rep,name=stuffCouponStuck" json:"stuffCouponStuck,omitempty"`
	UserId           uint64              `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
}

func (m *StuffUserCouponRequest) Reset()                    { *m = StuffUserCouponRequest{} }
func (m *StuffUserCouponRequest) String() string            { return proto.CompactTextString(m) }
func (*StuffUserCouponRequest) ProtoMessage()               {}
func (*StuffUserCouponRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *StuffUserCouponRequest) GetStuffCouponStuck() []*StuffCouponStuck {
	if m != nil {
		return m.StuffCouponStuck
	}
	return nil
}

func (m *StuffUserCouponRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type StuffUserCouponReply struct {
	Codes []uint64 `protobuf:"varint,1,rep,packed,name=codes" json:"codes,omitempty"`
	Err   *Error   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *StuffUserCouponReply) Reset()                    { *m = StuffUserCouponReply{} }
func (m *StuffUserCouponReply) String() string            { return proto.CompactTextString(m) }
func (*StuffUserCouponReply) ProtoMessage()               {}
func (*StuffUserCouponReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *StuffUserCouponReply) GetCodes() []uint64 {
	if m != nil {
		return m.Codes
	}
	return nil
}

func (m *StuffUserCouponReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type VerifyCouponRequest struct {
	Code           uint64 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ShopId         uint64 `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
	VerifierUserId uint64 `protobuf:"varint,3,opt,name=verifierUserId" json:"verifierUserId,omitempty"`
}

func (m *VerifyCouponRequest) Reset()                    { *m = VerifyCouponRequest{} }
func (m *VerifyCouponRequest) String() string            { return proto.CompactTextString(m) }
func (*VerifyCouponRequest) ProtoMessage()               {}
func (*VerifyCouponRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *VerifyCouponRequest) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VerifyCouponRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *VerifyCouponRequest) GetVerifierUserId() uint64 {
	if m != nil {
		return m.VerifierUserId
	}
	return 0
}

type VerifyCouponReply struct {
	UserCouponInfo *UserCouponInfo `protobuf:"bytes,1,opt,name=userCouponInfo" json:"userCouponInfo,omitempty"`
	Err            *Error          `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *VerifyCouponReply) Reset()                    { *m = VerifyCouponReply{} }
func (m *VerifyCouponReply) String() string            { return proto.CompactTextString(m) }
func (*VerifyCouponReply) ProtoMessage()               {}
func (*VerifyCouponReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *VerifyCouponReply) GetUserCouponInfo() *UserCouponInfo {
	if m != nil {
		return m.UserCouponInfo
	}
	return nil
}

func (m *VerifyCouponReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type CouponInfoByCodeRequest struct {
	Code   uint64 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	ShopId uint64 `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
}

func (m *CouponInfoByCodeRequest) Reset()                    { *m = CouponInfoByCodeRequest{} }
func (m *CouponInfoByCodeRequest) String() string            { return proto.CompactTextString(m) }
func (*CouponInfoByCodeRequest) ProtoMessage()               {}
func (*CouponInfoByCodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *CouponInfoByCodeRequest) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CouponInfoByCodeRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetVerificationCouponListRequest struct {
	ShopId             uint64 `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
	Name               string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	StartTime          string `protobuf:"bytes,3,opt,name=startTime" json:"startTime,omitempty"`
	EndTime            string `protobuf:"bytes,4,opt,name=endTime" json:"endTime,omitempty"`
	VerificationStatus uint32 `protobuf:"varint,5,opt,name=verificationStatus" json:"verificationStatus,omitempty"`
	VerifierUserId     uint64 `protobuf:"varint,6,opt,name=verifierUserId" json:"verifierUserId,omitempty"`
	Page               uint64 `protobuf:"varint,7,opt,name=page" json:"page,omitempty"`
	PageSize           uint64 `protobuf:"varint,8,opt,name=PageSize" json:"PageSize,omitempty"`
}

func (m *GetVerificationCouponListRequest) Reset()         { *m = GetVerificationCouponListRequest{} }
func (m *GetVerificationCouponListRequest) String() string { return proto.CompactTextString(m) }
func (*GetVerificationCouponListRequest) ProtoMessage()    {}
func (*GetVerificationCouponListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{11}
}

func (m *GetVerificationCouponListRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *GetVerificationCouponListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetVerificationCouponListRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetVerificationCouponListRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *GetVerificationCouponListRequest) GetVerificationStatus() uint32 {
	if m != nil {
		return m.VerificationStatus
	}
	return 0
}

func (m *GetVerificationCouponListRequest) GetVerifierUserId() uint64 {
	if m != nil {
		return m.VerifierUserId
	}
	return 0
}

func (m *GetVerificationCouponListRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetVerificationCouponListRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type VerificationCouponInfo struct {
	Code               uint64 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Name               string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	VerificationTime   string `protobuf:"bytes,3,opt,name=verificationTime" json:"verificationTime,omitempty"`
	CouponRelativeTime uint64 `protobuf:"varint,4,opt,name=couponRelativeTime" json:"couponRelativeTime,omitempty"`
	VerificationType   uint32 `protobuf:"varint,5,opt,name=verificationType" json:"verificationType,omitempty"`
	VerifierUserId     uint64 `protobuf:"varint,6,opt,name=verifierUserId" json:"verifierUserId,omitempty"`
	CouponType         uint32 `protobuf:"varint,7,opt,name=CouponType" json:"CouponType,omitempty"`
	StartTime          string `protobuf:"bytes,8,opt,name=startTime" json:"startTime,omitempty"`
	EndTime            string `protobuf:"bytes,9,opt,name=endTime" json:"endTime,omitempty"`
	ValidityType       uint32 `protobuf:"varint,10,opt,name=validityType" json:"validityType,omitempty"`
	CouponId           uint64 `protobuf:"varint,11,opt,name=couponId" json:"couponId,omitempty"`
}

func (m *VerificationCouponInfo) Reset()                    { *m = VerificationCouponInfo{} }
func (m *VerificationCouponInfo) String() string            { return proto.CompactTextString(m) }
func (*VerificationCouponInfo) ProtoMessage()               {}
func (*VerificationCouponInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *VerificationCouponInfo) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VerificationCouponInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VerificationCouponInfo) GetVerificationTime() string {
	if m != nil {
		return m.VerificationTime
	}
	return ""
}

func (m *VerificationCouponInfo) GetCouponRelativeTime() uint64 {
	if m != nil {
		return m.CouponRelativeTime
	}
	return 0
}

func (m *VerificationCouponInfo) GetVerificationType() uint32 {
	if m != nil {
		return m.VerificationType
	}
	return 0
}

func (m *VerificationCouponInfo) GetVerifierUserId() uint64 {
	if m != nil {
		return m.VerifierUserId
	}
	return 0
}

func (m *VerificationCouponInfo) GetCouponType() uint32 {
	if m != nil {
		return m.CouponType
	}
	return 0
}

func (m *VerificationCouponInfo) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *VerificationCouponInfo) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *VerificationCouponInfo) GetValidityType() uint32 {
	if m != nil {
		return m.ValidityType
	}
	return 0
}

func (m *VerificationCouponInfo) GetCouponId() uint64 {
	if m != nil {
		return m.CouponId
	}
	return 0
}

type GetVerificationCouponListReply struct {
	VerificationCouponInfoList []*VerificationCouponInfo `protobuf:"bytes,1,rep,name=verificationCouponInfoList" json:"verificationCouponInfoList,omitempty"`
	Count                      uint32                    `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Err                        *Error                    `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *GetVerificationCouponListReply) Reset()                    { *m = GetVerificationCouponListReply{} }
func (m *GetVerificationCouponListReply) String() string            { return proto.CompactTextString(m) }
func (*GetVerificationCouponListReply) ProtoMessage()               {}
func (*GetVerificationCouponListReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *GetVerificationCouponListReply) GetVerificationCouponInfoList() []*VerificationCouponInfo {
	if m != nil {
		return m.VerificationCouponInfoList
	}
	return nil
}

func (m *GetVerificationCouponListReply) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetVerificationCouponListReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func init() {
	proto.RegisterType((*UserCouponInfo)(nil), "coupon.pkg.rpc.protos.UserCouponInfo")
	proto.RegisterType((*GetUserCouponListReply)(nil), "coupon.pkg.rpc.protos.GetUserCouponListReply")
	proto.RegisterType((*GetUserCouponListRequest)(nil), "coupon.pkg.rpc.protos.GetUserCouponListRequest")
	proto.RegisterType((*GetUserCouponInfoRequest)(nil), "coupon.pkg.rpc.protos.GetUserCouponInfoRequest")
	proto.RegisterType((*GetUserCouponInfoReply)(nil), "coupon.pkg.rpc.protos.GetUserCouponInfoReply")
	proto.RegisterType((*StuffCouponStuck)(nil), "coupon.pkg.rpc.protos.StuffCouponStuck")
	proto.RegisterType((*StuffUserCouponRequest)(nil), "coupon.pkg.rpc.protos.StuffUserCouponRequest")
	proto.RegisterType((*StuffUserCouponReply)(nil), "coupon.pkg.rpc.protos.StuffUserCouponReply")
	proto.RegisterType((*VerifyCouponRequest)(nil), "coupon.pkg.rpc.protos.VerifyCouponRequest")
	proto.RegisterType((*VerifyCouponReply)(nil), "coupon.pkg.rpc.protos.VerifyCouponReply")
	proto.RegisterType((*CouponInfoByCodeRequest)(nil), "coupon.pkg.rpc.protos.CouponInfoByCodeRequest")
	proto.RegisterType((*GetVerificationCouponListRequest)(nil), "coupon.pkg.rpc.protos.GetVerificationCouponListRequest")
	proto.RegisterType((*VerificationCouponInfo)(nil), "coupon.pkg.rpc.protos.VerificationCouponInfo")
	proto.RegisterType((*GetVerificationCouponListReply)(nil), "coupon.pkg.rpc.protos.GetVerificationCouponListReply")
	proto.RegisterEnum("coupon.pkg.rpc.protos.UserCouponStatus", UserCouponStatus_name, UserCouponStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserCouponController service

type UserCouponControllerClient interface {
	// 优惠券列表
	GetUserCouponList(ctx context.Context, in *GetUserCouponListRequest, opts ...grpc.CallOption) (*GetUserCouponListReply, error)
	// 优惠券详情
	GetUserCouponInfo(ctx context.Context, in *GetUserCouponInfoRequest, opts ...grpc.CallOption) (*GetUserCouponInfoReply, error)
	// 通过 code 获取用户劵码
	GetCouponInfoByCode(ctx context.Context, in *CouponInfoByCodeRequest, opts ...grpc.CallOption) (*GetUserCouponInfoReply, error)
	// 发放优惠券接口 [多张优惠券]
	StuffUserCoupons(ctx context.Context, in *StuffUserCouponRequest, opts ...grpc.CallOption) (*StuffUserCouponReply, error)
	// 核销优惠券接口
	VerifyCoupon(ctx context.Context, in *VerifyCouponRequest, opts ...grpc.CallOption) (*VerifyCouponReply, error)
	// 核销列表接口
	GetVerificationCouponList(ctx context.Context, in *GetVerificationCouponListRequest, opts ...grpc.CallOption) (*GetVerificationCouponListReply, error)
}

type userCouponControllerClient struct {
	cc *grpc.ClientConn
}

func NewUserCouponControllerClient(cc *grpc.ClientConn) UserCouponControllerClient {
	return &userCouponControllerClient{cc}
}

func (c *userCouponControllerClient) GetUserCouponList(ctx context.Context, in *GetUserCouponListRequest, opts ...grpc.CallOption) (*GetUserCouponListReply, error) {
	out := new(GetUserCouponListReply)
	err := grpc.Invoke(ctx, "/coupon.pkg.rpc.protos.UserCouponController/GetUserCouponList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCouponControllerClient) GetUserCouponInfo(ctx context.Context, in *GetUserCouponInfoRequest, opts ...grpc.CallOption) (*GetUserCouponInfoReply, error) {
	out := new(GetUserCouponInfoReply)
	err := grpc.Invoke(ctx, "/coupon.pkg.rpc.protos.UserCouponController/GetUserCouponInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCouponControllerClient) GetCouponInfoByCode(ctx context.Context, in *CouponInfoByCodeRequest, opts ...grpc.CallOption) (*GetUserCouponInfoReply, error) {
	out := new(GetUserCouponInfoReply)
	err := grpc.Invoke(ctx, "/coupon.pkg.rpc.protos.UserCouponController/GetCouponInfoByCode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCouponControllerClient) StuffUserCoupons(ctx context.Context, in *StuffUserCouponRequest, opts ...grpc.CallOption) (*StuffUserCouponReply, error) {
	out := new(StuffUserCouponReply)
	err := grpc.Invoke(ctx, "/coupon.pkg.rpc.protos.UserCouponController/StuffUserCoupons", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCouponControllerClient) VerifyCoupon(ctx context.Context, in *VerifyCouponRequest, opts ...grpc.CallOption) (*VerifyCouponReply, error) {
	out := new(VerifyCouponReply)
	err := grpc.Invoke(ctx, "/coupon.pkg.rpc.protos.UserCouponController/VerifyCoupon", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCouponControllerClient) GetVerificationCouponList(ctx context.Context, in *GetVerificationCouponListRequest, opts ...grpc.CallOption) (*GetVerificationCouponListReply, error) {
	out := new(GetVerificationCouponListReply)
	err := grpc.Invoke(ctx, "/coupon.pkg.rpc.protos.UserCouponController/GetVerificationCouponList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserCouponController service

type UserCouponControllerServer interface {
	// 优惠券列表
	GetUserCouponList(context.Context, *GetUserCouponListRequest) (*GetUserCouponListReply, error)
	// 优惠券详情
	GetUserCouponInfo(context.Context, *GetUserCouponInfoRequest) (*GetUserCouponInfoReply, error)
	// 通过 code 获取用户劵码
	GetCouponInfoByCode(context.Context, *CouponInfoByCodeRequest) (*GetUserCouponInfoReply, error)
	// 发放优惠券接口 [多张优惠券]
	StuffUserCoupons(context.Context, *StuffUserCouponRequest) (*StuffUserCouponReply, error)
	// 核销优惠券接口
	VerifyCoupon(context.Context, *VerifyCouponRequest) (*VerifyCouponReply, error)
	// 核销列表接口
	GetVerificationCouponList(context.Context, *GetVerificationCouponListRequest) (*GetVerificationCouponListReply, error)
}

func RegisterUserCouponControllerServer(s *grpc.Server, srv UserCouponControllerServer) {
	s.RegisterService(&_UserCouponController_serviceDesc, srv)
}

func _UserCouponController_GetUserCouponList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCouponListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCouponControllerServer).GetUserCouponList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.pkg.rpc.protos.UserCouponController/GetUserCouponList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCouponControllerServer).GetUserCouponList(ctx, req.(*GetUserCouponListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCouponController_GetUserCouponInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCouponInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCouponControllerServer).GetUserCouponInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.pkg.rpc.protos.UserCouponController/GetUserCouponInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCouponControllerServer).GetUserCouponInfo(ctx, req.(*GetUserCouponInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCouponController_GetCouponInfoByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponInfoByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCouponControllerServer).GetCouponInfoByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.pkg.rpc.protos.UserCouponController/GetCouponInfoByCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCouponControllerServer).GetCouponInfoByCode(ctx, req.(*CouponInfoByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCouponController_StuffUserCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StuffUserCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCouponControllerServer).StuffUserCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.pkg.rpc.protos.UserCouponController/StuffUserCoupons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCouponControllerServer).StuffUserCoupons(ctx, req.(*StuffUserCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCouponController_VerifyCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCouponControllerServer).VerifyCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.pkg.rpc.protos.UserCouponController/VerifyCoupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCouponControllerServer).VerifyCoupon(ctx, req.(*VerifyCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserCouponController_GetVerificationCouponList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerificationCouponListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCouponControllerServer).GetVerificationCouponList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coupon.pkg.rpc.protos.UserCouponController/GetVerificationCouponList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCouponControllerServer).GetVerificationCouponList(ctx, req.(*GetVerificationCouponListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserCouponController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "coupon.pkg.rpc.protos.UserCouponController",
	HandlerType: (*UserCouponControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserCouponList",
			Handler:    _UserCouponController_GetUserCouponList_Handler,
		},
		{
			MethodName: "GetUserCouponInfo",
			Handler:    _UserCouponController_GetUserCouponInfo_Handler,
		},
		{
			MethodName: "GetCouponInfoByCode",
			Handler:    _UserCouponController_GetCouponInfoByCode_Handler,
		},
		{
			MethodName: "StuffUserCoupons",
			Handler:    _UserCouponController_StuffUserCoupons_Handler,
		},
		{
			MethodName: "VerifyCoupon",
			Handler:    _UserCouponController_VerifyCoupon_Handler,
		},
		{
			MethodName: "GetVerificationCouponList",
			Handler:    _UserCouponController_GetVerificationCouponList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userCoupon.proto",
}

func init() { proto.RegisterFile("userCoupon.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 910 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x5d, 0x6b, 0xf4, 0x44,
	0x14, 0x6e, 0x36, 0xd9, 0xaf, 0xb3, 0x6d, 0xc9, 0x3b, 0xad, 0x6b, 0x0c, 0x2f, 0x65, 0x0d, 0xa8,
	0x4b, 0xa5, 0x11, 0x56, 0xc5, 0xeb, 0xb7, 0xa5, 0x94, 0x82, 0x82, 0x64, 0xdd, 0x5e, 0x88, 0x28,
	0x31, 0x99, 0xad, 0xa1, 0xd9, 0x24, 0x66, 0x26, 0x8b, 0xeb, 0xbd, 0xe0, 0x8d, 0x5e, 0x08, 0x22,
	0xf8, 0x1f, 0xfc, 0x39, 0xfe, 0x05, 0x7f, 0x87, 0xcc, 0x4c, 0x3e, 0x37, 0xc9, 0x9a, 0x7a, 0x21,
	0x5e, 0xed, 0x9c, 0x93, 0x39, 0x1f, 0xf3, 0x9c, 0x73, 0x9e, 0xb3, 0xa0, 0x26, 0x04, 0xc7, 0x37,
	0x61, 0x12, 0x85, 0x81, 0x19, 0xc5, 0x21, 0x0d, 0xd1, 0x6b, 0x4e, 0x2a, 0x3d, 0x3d, 0x9a, 0x71,
	0xe4, 0x08, 0x2d, 0xd1, 0xcf, 0x84, 0xfa, 0x2b, 0x27, 0xdc, 0x6c, 0xb2, 0xbb, 0xfa, 0xb1, 0x53,
	0xb2, 0x34, 0x7e, 0xed, 0xc1, 0xe9, 0x2a, 0x77, 0x77, 0x1f, 0xac, 0x43, 0xf4, 0x0a, 0xc0, 0xc9,
	0x25, 0x4d, 0x9a, 0x49, 0xf3, 0xc9, 0xe2, 0x4d, 0xb3, 0x31, 0x82, 0x59, 0x98, 0x59, 0x25, 0x23,
	0x74, 0x01, 0x80, 0xbf, 0x8b, 0xbc, 0x18, 0x7f, 0xe6, 0x6d, 0xb0, 0xd6, 0x9b, 0x49, 0xf3, 0xb1,
	0x55, 0xd2, 0xa0, 0x29, 0x0c, 0x08, 0xb5, 0x69, 0x42, 0x34, 0x79, 0x26, 0xcd, 0x4f, 0xac, 0x54,
	0x42, 0x97, 0xa0, 0x6e, 0x71, 0xec, 0xad, 0x3d, 0xc7, 0xa6, 0x5e, 0x18, 0x70, 0x6b, 0x85, 0x5b,
	0xd7, 0xf4, 0xe8, 0x25, 0x8c, 0x9d, 0x18, 0xdb, 0x14, 0xbb, 0xaf, 0xa8, 0xd6, 0xe7, 0x97, 0x0a,
	0x05, 0x42, 0xa0, 0x38, 0xa1, 0x8b, 0xb5, 0xc1, 0x4c, 0x9a, 0x2b, 0x16, 0x3f, 0x33, 0x1d, 0xb1,
	0x7d, 0xaa, 0x0d, 0xf9, 0x65, 0x7e, 0x66, 0x99, 0x30, 0x34, 0xef, 0x5d, 0x6d, 0xc4, 0x6f, 0xa6,
	0x92, 0xf1, 0x87, 0x04, 0xd3, 0x3b, 0x4c, 0x0b, 0x68, 0x3e, 0xf6, 0x08, 0xb5, 0x70, 0xe4, 0xef,
	0xd0, 0x27, 0x70, 0x9a, 0x54, 0x10, 0xd3, 0xa4, 0x99, 0x3c, 0x9f, 0x2c, 0xde, 0x6a, 0xc1, 0xa8,
	0x0a, 0xaf, 0xb5, 0x67, 0x8c, 0x4c, 0x90, 0x71, 0x1c, 0x73, 0x90, 0x26, 0x8b, 0x97, 0x2d, 0x3e,
	0x6e, 0xe3, 0x38, 0x8c, 0x2d, 0x76, 0x11, 0x9d, 0x43, 0xdf, 0x09, 0x93, 0x80, 0xa6, 0xd0, 0x09,
	0xc1, 0xf8, 0x5d, 0x02, 0xad, 0x21, 0xdf, 0x6f, 0x13, 0x4c, 0xf8, 0x23, 0xc9, 0x37, 0x61, 0x74,
	0xef, 0xf2, 0x6a, 0x2a, 0x56, 0x2a, 0x95, 0x1e, 0xdf, 0x2b, 0x3f, 0xbe, 0xb5, 0x3c, 0x3a, 0x8c,
	0x7c, 0x9b, 0xd0, 0x1b, 0x06, 0xac, 0x28, 0x4b, 0x2e, 0xb3, 0x6f, 0x91, 0xfd, 0x88, 0x97, 0xde,
	0xf7, 0x98, 0x57, 0xe3, 0xc4, 0xca, 0x65, 0xe3, 0xcb, 0xbd, 0xdc, 0x38, 0x0e, 0x69, 0x6e, 0x59,
	0xa1, 0xa4, 0x52, 0xa1, 0x0e, 0xe5, 0x25, 0xde, 0x21, 0x97, 0xdf, 0x61, 0xfc, 0xb6, 0x5f, 0x2c,
	0x11, 0xa0, 0xad, 0x58, 0xd2, 0x7f, 0x56, 0x2c, 0xe3, 0x1a, 0xd4, 0x25, 0x4d, 0xd6, 0x6b, 0xe1,
	0x62, 0x49, 0x13, 0xe7, 0x89, 0x21, 0x95, 0x8e, 0x4a, 0x56, 0x8f, 0x5c, 0x66, 0x68, 0x04, 0xc9,
	0x86, 0xf0, 0x00, 0x27, 0x16, 0x3f, 0x1b, 0x3f, 0x48, 0x30, 0xe5, 0x4e, 0x8a, 0xdc, 0x32, 0xf0,
	0x96, 0xa0, 0x92, 0x3d, 0xf7, 0x69, 0x33, 0xbe, 0xd3, 0x92, 0xdb, 0x7e, 0x36, 0x56, 0xcd, 0x41,
	0x1b, 0xfa, 0xc6, 0x17, 0x70, 0x5e, 0x4b, 0x83, 0x41, 0xcc, 0x1b, 0xd2, 0xc5, 0x84, 0x47, 0x56,
	0x2c, 0x21, 0x3c, 0x1b, 0x29, 0x0f, 0xce, 0x1e, 0xd8, 0x88, 0xef, 0xaa, 0x2f, 0x6c, 0x69, 0x8f,
	0xb4, 0x0d, 0x7a, 0x95, 0x76, 0x7e, 0x1b, 0x4e, 0x05, 0x4b, 0xe0, 0x78, 0x25, 0x1e, 0x20, 0xda,
	0x64, 0x4f, 0x6b, 0xfc, 0x22, 0xc1, 0x8b, 0x6a, 0xac, 0xff, 0x41, 0xa7, 0xdc, 0xc2, 0xeb, 0x85,
	0xf5, 0xf5, 0x8e, 0xcd, 0xd4, 0xbf, 0xc0, 0xc0, 0xf8, 0xb9, 0x07, 0xb3, 0x3b, 0x4c, 0x1f, 0x4a,
	0x6c, 0xd9, 0x9d, 0x0f, 0x58, 0xf7, 0xd9, 0x39, 0x61, 0xf3, 0x33, 0xa3, 0x59, 0x42, 0xed, 0x98,
	0x72, 0x2e, 0x96, 0x05, 0xcd, 0xe6, 0x0a, 0xa4, 0xc1, 0x10, 0x07, 0x6e, 0x89, 0xa7, 0x33, 0x11,
	0x99, 0x80, 0xca, 0x94, 0xbd, 0x14, 0x7c, 0x22, 0x98, 0xa1, 0xe1, 0x4b, 0x43, 0xf1, 0x06, 0x4d,
	0xc5, 0x63, 0x39, 0x32, 0x5e, 0xe1, 0x24, 0xae, 0x58, 0xfc, 0xcc, 0x26, 0xea, 0xd3, 0x8c, 0x7b,
	0x04, 0x8d, 0xe7, 0xb2, 0xf1, 0xa3, 0x0c, 0xd3, 0x3a, 0x1a, 0xbc, 0x44, 0x4d, 0xb8, 0x36, 0x41,
	0xd0, 0xb4, 0x95, 0xe4, 0x96, 0xad, 0x64, 0x02, 0x72, 0xd2, 0xa6, 0xf2, 0x6d, 0xea, 0x6d, 0x71,
	0x8e, 0x8d, 0x62, 0x35, 0x7c, 0xa9, 0xf9, 0xde, 0x45, 0x19, 0x7d, 0xd6, 0xf4, 0x9d, 0x21, 0xba,
	0x00, 0x10, 0xaf, 0xe4, 0xde, 0x86, 0xdc, 0x5b, 0x49, 0x53, 0x2d, 0xe9, 0xe8, 0x40, 0x49, 0xc7,
	0xd5, 0x92, 0x1a, 0x70, 0xbc, 0xb5, 0x7d, 0xcf, 0xf5, 0xe8, 0x8e, 0x7b, 0x06, 0xee, 0xb9, 0xa2,
	0xab, 0x90, 0xdb, 0xa4, 0x4a, 0x6e, 0xc6, 0x9f, 0x12, 0x5c, 0x1c, 0xe8, 0x4d, 0x36, 0x84, 0x1b,
	0xd0, 0xb7, 0x8d, 0xc5, 0x62, 0x57, 0x52, 0x6a, 0xbb, 0x6a, 0x19, 0xa6, 0xe6, 0x2a, 0x5b, 0x07,
	0x1c, 0x16, 0xbb, 0xb4, 0x57, 0xda, 0xa5, 0xd9, 0xe8, 0xca, 0x1d, 0x47, 0xf7, 0xf2, 0x03, 0x50,
	0x0b, 0x32, 0x48, 0xdb, 0x79, 0x0c, 0xfd, 0x55, 0xb0, 0x22, 0x58, 0x3d, 0x42, 0x23, 0x50, 0x56,
	0x04, 0xbb, 0xaa, 0x84, 0x26, 0x30, 0xbc, 0xe5, 0x7f, 0x82, 0x5c, 0xb5, 0xb7, 0xf8, 0xab, 0x0f,
	0xe7, 0x85, 0xd9, 0x4d, 0x18, 0xd0, 0x38, 0xf4, 0x7d, 0x1c, 0xa3, 0x04, 0x5e, 0xd4, 0x36, 0x39,
	0x7a, 0xaf, 0x25, 0x8d, 0xb6, 0x9d, 0xaf, 0x5f, 0x75, 0x37, 0x88, 0xfc, 0x9d, 0x71, 0x54, 0x0b,
	0xcb, 0x47, 0xa4, 0x53, 0xd8, 0xd2, 0x3a, 0xef, 0x16, 0x36, 0x5f, 0xcf, 0xc6, 0x11, 0xda, 0xc2,
	0xd9, 0x1d, 0xa6, 0xfb, 0xd4, 0x87, 0xcc, 0x7f, 0xfc, 0xc3, 0x59, 0xe1, 0xc8, 0xe7, 0xc7, 0x8d,
	0xd2, 0xcd, 0x5c, 0x7c, 0x25, 0xe8, 0xea, 0xd0, 0xd2, 0xac, 0x6d, 0x5f, 0xfd, 0xdd, 0xae, 0xd7,
	0x45, 0xc4, 0x35, 0x1c, 0x97, 0xb7, 0x0e, 0xba, 0x3c, 0xd4, 0xc7, 0xd5, 0x35, 0xa8, 0xcf, 0x3b,
	0xdd, 0x15, 0x71, 0x7e, 0x92, 0xe0, 0x8d, 0xd6, 0x31, 0x43, 0x1f, 0xb5, 0x03, 0x75, 0x70, 0x69,
	0xe8, 0x1f, 0x3e, 0xdf, 0x90, 0xe7, 0x73, 0x3d, 0xfa, 0x7c, 0x20, 0xae, 0x7e, 0x2d, 0x7e, 0xdf,
	0xff, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x06, 0xbf, 0x58, 0xc1, 0x0c, 0x00, 0x00,
}
